在调用函数过程中发生异常,对象来不及析构。可以在catch块中析构。
也可以使用auto_ptr来处理。在其被销毁之前(由于即将离开其scope)删除它。
auto_ptr----->以一个对象存放必须自动释放的资源。并依赖该对象的的身体乳才通人释放。亦可对一直震为本意外的资源施行。

c++保证删除null指针是安全的。
c++只会析构已经构造完的对象。

BookEntry  *pb=0;
try{
	pb=new BookEntry("aaa");
}catch(...){
	delete pb;
	throw;
}
delete pb;

除非new动作成功,否则上述那个assignment动作不会施加于pb上。故还是会内存泄露。delete的还是null。

把共享代码抽出放到一个private辅助函数调用中。


调用一个函数,控制权最终会回到调用端。(除非函数调用失败以至于无法返回)。但是跑出一个异常,控制权最终不会回到抛出端。

